language:
- python
python:
- 3.5
branches:
  only:
  - master
script:
- python setup.py install
- make lint
- make test
after_success:
- pip install python-coveralls
- coveralls
deploy:
  provider: pages
  local_dir: "docs/html"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
