branches:
  except:
  - gh-pages
language:
- python
python:
- 3.2
- 3.3
- 3.4
- 3.5
- 3.6
- nightly
script:
- python setup.py install
- make pre-commit
after_success:
# Only publish docs and coverage if it's a non-pull request on master with
# python 3.5.
- [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] || { echo "Pull request."; exit 0; }
- [[ "${TRAVIS_BRANCH}" == "master" ]] || { echo "Non-master."; exit 0; }
- [[ "${TRAVIS_PYTHON_VERSION}" == "3.5" ]] || { echo "Non 3.5."; exit 0; }
- pip install python-coveralls
- coveralls
- >-
  openssl aes-256-cbc
  -K $encrypted_bfd322024369_key
  -iv $encrypted_bfd322024369_iv
  -in travis_github_deploy_key.enc
  -out travis_github_deploy_key
  -d
- chmod 0600 travis_github_deploy_key
- cp travis_github_deploy_key ~/.ssh/id_rsa
- make docs-publish
