language:
- python
python:
- 3.5
branches:
  only:
  - master
script:
- python setup.py install
- make pre-commit
after_success:
- pip install python-coveralls
- coveralls
- >-
  openssl aes-256-cbc
  -K $encrypted_bfd322024369_key
  -iv $encrypted_bfd322024369_iv
  -in travis_github_deploy_key.enc
  -out travis_github_deploy_key
  -d
- chmod 0600 travis_github_deploy_key
- cp travis_github_deploy_key ~/.ssh/id_rsa
- make docs-publish
